@startuml Shape UML
scale 2
title Shape UML

class Palindrome{
    ... private members ...
    - _cost: float
    - _title: str

    ... special methods ...
    - __init__(): None
    - __str__(): str
    - __repr__(): str

    ... instance/public method ...
    + find_cost(): float
}
@enduml